import api from './client';

export type ItemUrgency = 'Upcoming' | 'DueThisWeek' | 'Overdue';
export type ItemSource = 'AutoGenerated' | 'Manual';
export type ListStatus = 'Active' | 'InProgress' | 'Completed' | 'Archived';
export type PurchaseFrequency =
  | 'Unknown'
  | 'Weekly'
  | 'Fortnightly'
  | 'Monthly'
  | 'Quarterly'
  | 'Annually'
  | 'Occasional';

export interface GenerateListRequest {
  familyId: string;
  includeDueItems?: boolean;
  includeOverdueItems?: boolean;
  includeUpcomingItems?: boolean;
  categoryFilter?: string[];
  listName?: string;
  createdBy: string;
}

export interface ListItem {
  productId: string;
  productName: string;
  categoryName?: string;
  urgency: ItemUrgency;
  quantity: number;
  lastPurchased?: string;
  frequency?: PurchaseFrequency;
  daysSinceLastPurchase: number;
  notes?: string;
}

export interface ListMetadata {
  totalItems: number;
  overdueCount: number;
  dueThisWeekCount: number;
  upcomingCount: number;
  categoriesIncluded: string[];
  generatedDate: string;
}

export interface GeneratedListResponse {
  listId: string;
  listName: string;
  items: ListItem[];
  metadata: ListMetadata;
}

export interface ProductSuggestion {
  productId: string;
  productName: string;
  categoryName?: string;
  urgency: ItemUrgency;
  recommendedQuantity: number;
  reason: string;
}

export interface ProductSuggestionsResponse {
  overdueCount: number;
  dueThisWeekCount: number;
  upcomingCount: number;
  suggestions: ProductSuggestion[];
}

export interface ShoppingList {
  id: string;
  familyId: string;
  name: string;
  createdBy: string;
  createdDate: string;
  status: ListStatus;
  sharedWith?: string; // JSON array of user IDs
  completedDate?: string;
  items: ShoppingListItem[];
}

export interface ShoppingListItem {
  id: string;
  listId: string;
  productId: string;
  quantity: number;
  isPurchased: boolean;
  urgency: ItemUrgency;
  addedBy: string;
  source: ItemSource;
  addedDate: string;
  purchasedDate?: string;
  // Navigation properties
  product?: {
    id: string;
    name: string;
    categoryId?: string;
    categoryName?: string;
    notes?: string; // Product notes for reference
    tags?: string; // JSON string of tags
  };
}

export interface AddItemRequest {
  productId: string;
  quantity: number;
  urgency: ItemUrgency;
  addedBy: string;
}

export interface UpdatePurchaseStatusRequest {
  isPurchased: boolean;
}

export interface ArchiveResult {
  archivedCount: number;
  familyId: string;
  daysOld: number;
}

/**
 * API client for shopping list generation and management
 */
export const shoppingListApi = {
  /**
   * Generate a shopping list based on purchase frequencies (FR-017)
   */
  async generateList(request: GenerateListRequest): Promise<GeneratedListResponse> {
    const response = await api.post<GeneratedListResponse>(
      '/api/listgenerator/generate',
      request
    );
    return response.data;
  },

  /**
   * Get product suggestions without creating a list
   */
  async getSuggestions(familyId: string): Promise<ProductSuggestionsResponse> {
    const response = await api.get<ProductSuggestionsResponse>(
      '/api/listgenerator/suggestions',
      {
        params: { familyId }
      }
    );
    return response.data;
  },

  /**
   * Get all shopping lists for a family
   */
  async getListsByFamily(familyId: string): Promise<ShoppingList[]> {
    const response = await api.get<ShoppingList[]>(
      `/api/listgenerator/${familyId}`
    );
    return response.data;
  },

  /**
   * Get active shopping lists for a family
   */
  async getActiveListsByFamily(familyId: string): Promise<ShoppingList[]> {
    const response = await api.get<ShoppingList[]>(
      `/api/listgenerator/${familyId}/active`
    );
    return response.data;
  },

  /**
   * Get a specific shopping list by ID
   */
  async getListById(listId: string): Promise<ShoppingList> {
    const response = await api.get<ShoppingList>(
      `/api/listgenerator/list/${listId}`
    );
    return response.data;
  },

  /**
   * Add item to shopping list (FR-019)
   */
  async addItemToList(
    listId: string,
    item: AddItemRequest
  ): Promise<ShoppingListItem> {
    const response = await api.post<ShoppingListItem>(
      `/api/listgenerator/list/${listId}/items`,
      item
    );
    return response.data;
  },

  /**
   * Remove item from shopping list
   */
  async removeItemFromList(itemId: string): Promise<void> {
    await api.delete(`/api/listgenerator/list/items/${itemId}`);
  },

  /**
   * Mark item as purchased/unpurchased
   */
  async updateItemPurchaseStatus(
    itemId: string,
    isPurchased: boolean
  ): Promise<ShoppingListItem> {
    const response = await api.patch<ShoppingListItem>(
      `/api/listgenerator/list/items/${itemId}/purchase`,
      { isPurchased }
    );
    return response.data;
  },

  /**
   * Complete a shopping list
   */
  async completeList(listId: string): Promise<ShoppingList> {
    const response = await api.post<ShoppingList>(
      `/api/listgenerator/list/${listId}/complete`
    );
    return response.data;
  },

  /**
   * Archive old completed lists (FR-020)
   */
  async archiveOldLists(
    familyId: string,
    daysOld: number = 30
  ): Promise<ArchiveResult> {
    const response = await api.post<ArchiveResult>(
      `/api/listgenerator/${familyId}/archive`,
      null,
      {
        params: { daysOld }
      }
    );
    return response.data;
  },

  /**
   * Create a new empty shopping list (T163)
   */
  async createList(
    familyId: string,
    name: string,
    createdBy: string
  ): Promise<ShoppingList> {
    const response = await api.post<ShoppingList>(
      `/api/listgenerator/list`,
      {
        familyId,
        name,
        createdBy
      }
    );
    return response.data;
  },

  /**
   * Archive a specific shopping list (T167)
   */
  async archiveList(listId: string): Promise<ShoppingList> {
    const response = await api.post<ShoppingList>(
      `/api/listgenerator/${listId}/archive`
    );
    return response.data;
  },

  /**
   * Restore an archived shopping list (T167)
   */
  async restoreList(listId: string): Promise<ShoppingList> {
    const response = await api.post<ShoppingList>(
      `/api/listgenerator/${listId}/restore`
    );
    return response.data;
  },

  /**
   * Copy an existing shopping list (T162)
   */
  async copyList(
    listId: string,
    newName: string,
    copiedBy: string
  ): Promise<ShoppingList> {
    const response = await api.post<ShoppingList>(
      `/api/listgenerator/${listId}/copy`,
      {
        newName,
        copiedBy
      }
    );
    return response.data;
  }
};
